work on config stuff

diff --git a/transcrypt b/transcrypt
--- a/transcrypt
+++ b/transcrypt
@@ -92,6 +92,175 @@ _set_global(){
     printf -v "$key" '%s' "$val"
 }
 
+
+_validate_variable_str(){
+    #__doc__='
+    #Checks if the target variable is in the set of valid values.
+    #If it is not, it unsets the target variable, then if not in interactive
+    #mode it calls die.
+    #Args:
+    #    varname: name of variable to validate
+    #    valid_values: space separated string of valid values
+    #'
+    local varname=$1
+    local valid_values=$2
+    local varval=${!varname}
+    if ! _is_contained_str "$varval" "$valid_values"; then
+        message=$(printf '%s is `%s`, but must be one of: %s' "$varname" "$varval" "$valid_values")
+		if [[ $interactive ]]; then
+            _set_global "$varname" ""
+            echo "$message"
+		else
+            die 1 "$message"
+        fi
+    fi
+}
+
+_get_user_input() {
+    # Helper to prompt the user, store a response, and validate the result
+    # Args:
+    #     varname : name of the bash variable to populate
+    #     default : the default value to use if the user provides no answer
+    #     validate_fn : the name of a function that validates the user input
+    #     prompt : string to present to the user
+    local varname=$1
+    local default=$2
+    local validate_fn=$3
+    local prompt=$4
+
+	while [[ ! ${!varname} ]]; do
+		local answer=
+		if [[ $interactive ]]; then
+			printf '%s' "$prompt"
+			read -r answer
+		fi
+        # use the default value if the user gave no answer; otherwise call the
+        # validate function, which should set the varname to empty if it is
+        # invalid and the user should continue, otherwise it should die.
+		if [[ ! $answer ]]; then
+            _set_global "$varname" "$default"
+		else
+            _set_global "$varname" "$answer"
+            ${validate_fn}
+		fi
+	done
+}
+
+
+_openssl_list(){
+    # Args: the openssl commands to list
+    arg=$1
+	if "${openssl_path}  list-$arg" &>/dev/null; then
+		# OpenSSL < v1.1.0
+		"${openssl_path}" "list-$arg"
+	else
+		# OpenSSL >= v1.1.0
+		"${openssl_path}" "list" "-$arg"
+	fi
+}
+
+_is_contained_str(){
+    __doc__='
+    Args:
+        arg : the query to check if it is contained in the values
+        values : a string of space separated values
+
+    Example:
+        # Demo using raw call
+        (_is_contained_str "foo" "foo bar baz" && echo "contained") || echo "missing"
+        (_is_contained_str "bar" "foo bar baz" && echo "contained") || echo "missing"
+        (_is_contained_str "baz" "foo bar baz" && echo "contained") || echo "missing"
+        (_is_contained_str "biz" "foo bar baz" && echo "contained") || echo "missing"
+        # Demo using variables
+        arg="bar"
+        values="foo bar baz"
+        (_is_contained_str "$arg" "$values" && echo "contained") || echo "missing"
+    '
+    arg=$1
+    values=$2
+    echo "$values" | tr -s ' ' '\n'  | grep -Fx "$arg" &>/dev/null
+}
+
+_load_versioned_config_var(){
+    local key=$1
+    # Test for blocked variables that should not go into a plaintext config file
+    if _is_contained_str "${key}" "${VERSIONED_CONFIG_BLOCKLIST}"; then
+        warn "Cannot use ${key} in versioned the transcrypt config"
+        return 1
+    fi
+    git config --file "${VERSIONED_TC_CONFIG}" --get "${key}" || true
+}
+
+_set_versioned_config_var(){
+    local key=$1
+    local val=$2
+    # Test for blocked variables that should not go into a plaintext config file
+    if _is_contained_str "${key}" "${VERSIONED_CONFIG_BLOCKLIST}"; then
+        warn "Cannot use ${key} in versioned the transcrypt config"
+        return 1
+    fi
+    mkdir -p "${VERSIONED_TC_DIR}"
+    git config --file "${VERSIONED_TC_CONFIG}" "${key}" "${val}"
+}
+
+_load_config_var(){
+    # First try loading from the local checkout-independent .git/config file
+    # If that doesn't work, then look in the .transcrypt/config file
+    # (which is expected to be stored in plaintext and checked into the repo)
+    # Certain values will be blocked from being placed here (like the password)
+    local key=$1
+    git config --get --local "${key}"
+	if [[ "$?" != "0" ]]; then
+        _load_versioned_config_var "${key}"
+	fi
+}
+
+# shellcheck disable=SC2155
+_load_transcrypt_config_vars(){
+    # Populate bash vars with our config
+	cipher=$(git config --get --local transcrypt.cipher)
+    digest=$(git config --get --local transcrypt.digest)
+    use_pbkdf2=$(git config --get --local transcrypt.use-pbkdf2)
+    salt_method=$(git config --get --local transcrypt.salt-method)
+
+	password=$(git config --get --local transcrypt.password)
+	openssl_path=$(git config --get --local transcrypt.openssl-path)
+
+	# the current git repository's top-level directory
+	readonly REPO=$(git rev-parse --show-toplevel 2>/dev/null)
+
+    # This is the place where transcrypt can store state that will be
+    # "versioned" (i.e. checked into the repo)
+    readonly VERSIONED_TC_DIR="${REPO}/.transcrypt"
+    readonly VERSIONED_TC_CONFIG="${VERSIONED_TC_DIR}/config"
+}
+
+
+_load_vars_for_encryption(){
+    # Helper to populate variables needed to call openssl encryption
+    _load_transcrypt_config_vars
+
+    if [[ "$use_pbkdf2" == "1" ]]; then
+        pbkdf2_args=('-pbkdf2')
+    else
+        pbkdf2_args=()
+    fi
+
+    if [[ "$salt_method" == "password" ]]; then
+        extra_salt=$password
+    elif [[ "$salt_method" == "configured" ]]; then
+        extra_salt=$(_load_versioned_config_var "transcrypt.extra-salt")
+    else
+        die "unknown salt method"
+    fi
+
+    if [[ "$extra_salt" == "" ]]; then 
+        die "Extra salt is not set"
+    fi
+}
+
+
+
 # establish repository metadata and directory handling
 # shellcheck disable=SC2155
 gather_repo_metadata() {
@@ -164,117 +333,6 @@ die() {
 # proven to be a PRF, so we generate an HMAC-SHA256 for each decrypted file
 # (keyed with a combination of the filename and ~~transcrypt password~~), and
 # then use the last 16 bytes of that HMAC for the file's unique salt.
-
-
-# shellcheck disable=SC2155
-_check_config_poc(){
-    # Notes on custom config
-    # https://unix.stackexchange.com/questions/175648/use-config-file-for-my-shell-script
-    mkdir -p "${VERSIONED_CONFIG_DPATH}"
-    touch "${VERSIONED_TC_CONFIG}"
-    git config -f "$VERSIONED_TC_CONFIG" --get transcrypt.cipher
-    git config -f "$VERSIONED_TC_CONFIG" --get transcrypt.rotating.salt
-
-    # POC for using git to store cross-checkout configs 
-    extra_salt=$(openssl rand -hex 32)
-    git config --file "${VERSIONED_TC_CONFIG}" transcrypt.cipher "aes-256-cbc"
-    git config --file "${VERSIONED_TC_CONFIG}" transcrypt.use-pbkdf2 "true" --type=bool
-    git config --file "${VERSIONED_TC_CONFIG}" transcrypt.digest "SHA512"
-    git config --file "${VERSIONED_TC_CONFIG}" transcrypt.salt-method "auto"
-    git config --file "${VERSIONED_TC_CONFIG}" transcrypt.extra-salt "${extra_salt}"
-}
-
-
-_is_contained_str(){
-    __doc__='
-    Args:
-        arg : the query to check if it is contained in the values
-        values : a string of space separated values
-
-    Example:
-        # Demo using raw call
-        (_is_contained_str "foo" "foo bar baz" && echo "contained") || echo "missing"
-        (_is_contained_str "bar" "foo bar baz" && echo "contained") || echo "missing"
-        (_is_contained_str "baz" "foo bar baz" && echo "contained") || echo "missing"
-        (_is_contained_str "biz" "foo bar baz" && echo "contained") || echo "missing"
-        # Demo using variables
-        arg="bar"
-        values="foo bar baz"
-        (_is_contained_str "$arg" "$values" && echo "contained") || echo "missing"
-    '
-    arg=$1
-    values=$2
-    echo "$values" | tr -s ' ' '\n'  | grep -Fx "$arg" &>/dev/null
-}
-
-_load_versioned_config_var(){
-    local key=$1
-    # Test for blocked variables that should not go into a plaintext config file
-    if _is_contained_str "${key}" "${VERSIONED_CONFIG_BLOCKLIST}"; then
-        warn "Cannot use ${key} in versioned the transcrypt config"
-        return 1
-    fi
-    git config --file "${VERSIONED_TC_CONFIG}" --get "${key}"
-}
-
-_set_versioned_config_var(){
-    local key=$1
-    local val=$1
-    # Test for blocked variables that should not go into a plaintext config file
-    if _is_contained_str "${key}" "${VERSIONED_CONFIG_BLOCKLIST}"; then
-        warn "Cannot use ${key} in versioned the transcrypt config"
-        return 1
-    fi
-    mkdir -p "${VERSIONED_TC_DIR}"
-    git config --file "${VERSIONED_TC_CONFIG}" "${key}" "${val}"
-}
-
-_load_config_var(){
-    # First try loading from the local checkout-independent .git/config file
-    # If that doesn't work, then look in the .transcrypt/config file
-    # (which is expected to be stored in plaintext and checked into the repo)
-    # Certain values will be blocked from being placed here (like the password)
-    local key=$1
-    git config --get --local "${key}"
-	if [[ "$?" != "0" ]]; then
-        _load_versioned_config_var "${key}"
-	fi
-}
-
-_load_transcrypt_config_vars(){
-    # Populate bash vars with our config
-	cipher=$(git config --get --local transcrypt.cipher)
-    digest=$(git config --get --local transcrypt.digest)
-    use_pbkdf2=$(git config --get --local transcrypt.use-pbkdf2)
-    salt_method=$(git config --get --local transcrypt.salt-method)
-
-	password=$(git config --get --local transcrypt.password)
-	openssl_path=$(git config --get --local transcrypt.openssl-path)
-}
-
-_load_vars_for_encryption(){
-    # Helper to populate variables needed to call openssl encryption
-    _load_transcrypt_config_vars
-
-    if [[ "$use_pbkdf2" == "1" ]]; then
-        pbkdf2_args=('-pbkdf2')
-    else
-        pbkdf2_args=()
-    fi
-
-    if [[ "$salt_method" == "password" ]]; then
-        extra_salt=$password
-    elif [[ "$salt_method" == "configured" ]]; then
-        extra_salt=$(_load_versioned_config_var "transcrypt.extra-salt")
-    else
-        die "unknown salt method"
-    fi
-
-    if [[ "$extra_salt" == "" ]]; then 
-        die "Extra salt is not set"
-    fi
-}
-
 git_clean() {
 
 	# The clean script encrypts files before git sends them to the remote.
@@ -482,63 +540,17 @@ run_safety_checks() {
 	fi
 }
 
-
-_openssl_list(){
-    # Args: the openssl commands to list
-    arg=$1
-	if "${openssl_path}  list-$arg" &>/dev/null; then
-		# OpenSSL < v1.1.0
-		"${openssl_path}" "list-$arg"
-	else
-		# OpenSSL >= v1.1.0
-		"${openssl_path}" "list" "-$arg"
-	fi
-}
-
-
-
 # unset the cipher variable if it is not supported by openssl
 validate_cipher() {
     local valid_ciphers
     valid_ciphers=$(_openssl_list cipher-commands)
     _validate_variable_str "cipher" "$valid_ciphers"
-	#local list_cipher_commands
-    #list_cipher_commands="_openssl_list cipher-commands"
-	#local supported
-	#supported=$($list_cipher_commands | tr -s ' ' '\n' | grep -Fx "$cipher") || true
-	#if [[ ! $supported ]]; then
-	#    if [[ $interactive ]]; then
-	#        printf '"%s" is not a valid cipher; choose one of the following:\n\n' "$cipher"
-	#        $list_cipher_commands | column -c 80
-	#        printf '\n'
-	#        cipher=''
-	#    else
-	#        # shellcheck disable=SC2016
-	#        die 1 '"%s" is not a valid cipher; see `%s`' "$cipher" "$list_cipher_commands"
-	#    fi
-	#fi
 }
-
 
 validate_digest() {
     local valid_digests
     valid_digests=$(_openssl_list digest-commands)
     _validate_variable_str "digest" "$valid_digests"
-	#local list_digest_commands
-    #list_digest_commands="_openssl_list digest-commands"
-	#local supported
-	#supported=$($list_digest_commands | tr -s ' ' '\n' | grep -Fxi "$digest") || true
-	#if [[ ! $supported ]]; then
-	#    if [[ $interactive ]]; then
-	#        printf '"%s" is not a valid digest; choose one of the following:\n\n' "$digest"
-	#        $list_digest_commands | column -c 80
-	#        printf '\n'
-	#        digest=''
-	#    else
-	#        # shellcheck disable=SC2016
-	#        die 1 '"%s" is not a valid digest; see `%s`' "$digest" "$list_digest_commands"
-	#    fi
-	#fi
 }
 
 validate_use_pbkdf2() {
@@ -549,101 +561,6 @@ validate_use_pbkdf2() {
 validate_salt_method(){
     _validate_variable_str "salt_method" "$VALID_SALT_METHODS"
 }
-
-_validate_variable_str(){
-    __doc__='
-    Checks if the target variable is in the set of valid values.
-    If it is not, it unsets the target variable, then if not in interactive
-    mode it calls die.
-
-    Args:
-        varname: name of variable to validate
-        valid_values: space separated string of valid values
-    '
-    local varname=$1
-    local valid_values=$2
-    local varval=${!varname}
-    if ! _is_contained_str "$varval" "$valid_values"; then
-        message=$(printf '%s is `%s`, but must be one of: %s' "$varname" "$varval" "$valid_values")
-		if [[ $interactive ]]; then
-            _set_global "$varname" ""
-            echo "$message"
-		else
-            die 1 "$message"
-        fi
-    fi
-}
-
-_get_user_input() {
-    # Helper to prompt the user, store a response, and validate the result
-    # Args:
-    #     varname : name of the bash variable to populate
-    #     default : the default value to use if the user provides no answer
-    #     validate_fn : the name of a function that validates the user input
-    #     prompt : string to present to the user
-    local varname=$1
-    local default=$2
-    local validate_fn=$3
-    local prompt=$4
-
-	while [[ ! ${!varname} ]]; do
-		local answer=
-		if [[ $interactive ]]; then
-			printf '%s' "$prompt"
-			read -r answer
-		fi
-        # use the default value if the user gave no answer; otherwise call the
-        # validate function, which should set the varname to empty if it is
-        # invalid and the user should continue, otherwise it should die.
-		if [[ ! $answer ]]; then
-            _set_global "$varname" "$default"
-		else
-            _set_global "$varname" "$answer"
-            ${validate_fn}
-		fi
-	done
-}
-
-
-_get_user_input2() {
-    __doc__='
-    Helper to prompt the user, store a response, and validate the result
-    Args:
-        varname : name of the bash variable to populate
-        default : the default value to use if the user provides no answer
-        valid_values: space separated string of valid values
-        prompt : string to present to the user
-
-    Example:
-        source ~/code/transcrypt/bash_helpers.sh
-        interactive=1
-        myvar=
-        echo "myvar = <$myvar>"
-        _get_user_input2 "myvar" "a" "a b c" "choose one"
-    '
-    local varname=$1
-    local default=$2
-    local valid_values=$3
-    local prompt=$4
-
-	while [[ ! ${!varname} ]]; do
-		local answer=
-		if [[ $interactive ]]; then
-			printf '%s > ' "$prompt"
-			read -r answer
-		fi
-        # use the default value if the user gave no answer; otherwise call the
-        # validate function, which should set the varname to empty if it is
-        # invalid and the user should continue, otherwise it should die.
-		if [[ ! $answer ]]; then
-            _set_global "$varname" "$default"
-		else
-            _set_global "$varname" "$answer"
-            _validate_variable_str "$varname" "$valid_values"
-		fi
-	done
-}
-
 
 # ensure we have a digest to hash the salted password
 get_digest() {
@@ -817,10 +734,21 @@ save_configuration() {
 
     use_versioned_config=1
     if [[ "$use_versioned_config" == "1" ]]; then
+        _set_versioned_config_var "transcrypt.version" "$VERSION"
         _set_versioned_config_var "transcrypt.cipher" "$cipher"
         _set_versioned_config_var "transcrypt.digest" "$digest"
         _set_versioned_config_var "transcrypt.use-pbkdf2" "$use_pbkdf2"
+        _set_versioned_config_var "transcrypt.salt-method" "$salt_method"
         #_set_versioned_config_var "transcrypt.extra-salt" "$use_pbkdf2"
+    fi
+    if [[ "$salt_method" == "configured" ]]; then
+        git config transcrypt.extra-salt "$extra_salt"
+        _set_versioned_config_var "transcrypt.extra-salt" "$extra_salt"
+        if ! git ls-files --error-unmatch "$VERSIONED_TC_CONFIG"; then
+            echo "When using a configured salt method, you must commit "
+            echo "the ${VERSIONED_TC_CONFIG} file to the repo in order "
+            echo "to get consistent encryption across machines"
+        fi
     fi
 
 	# write the filter settings. Sorry for the horrific quote escaping below...
@@ -852,6 +780,9 @@ _display_runtime_configuration(){
 	printf '  DIGEST:  %s\n' "$digest"
 	printf '  USE_PBKDF2: %s\n' "$use_pbkdf2"
 	printf '  SALT_METHOD: %s\n' "$salt_method"
+    if [[ "$salt_method" == "configured" ]]; then
+        printf '  EXTRA_SALT: %s\n' "$extra_salt"
+    fi
 	printf '  CIPHER:   %s\n' "$cipher"
 	printf '  PASSWORD: %s\n\n' "$password"
 }
@@ -874,6 +805,12 @@ display_configuration() {
 	current_password=$(git config --get --local transcrypt.password)
 	local escaped_password=${current_password//\'/\'\\\'\'}
 
+    local current_extra_salt
+    if [[ "$current_salt_method" == "configured" ]]; then
+        current_extra_salt=$(_load_versioned_config_var "transcrypt.extra-salt")
+        echo "current_extra_salt = $current_extra_salt"
+    fi
+
 	printf 'The current repository was configured using transcrypt version %s\n' "$CONFIGURED"
 	printf 'and has the following configuration:\n\n'
 	[[ ! $REPO ]] || printf '  GIT_WORK_TREE:  %s\n' "$REPO"
@@ -882,10 +819,14 @@ display_configuration() {
 	printf '  DIGEST:  %s\n' "$current_digest"
 	printf '  USE_PBKDF2: %s\n' "$current_use_pbkdf2"
 	printf '  SALT_METHOD: %s\n' "$current_salt_method"
+    if [[ "$current_salt_method" == "configured" ]]; then
+        printf '  EXTRA_SALT: %s\n' "$current_extra_salt"
+    fi
 	printf '  CIPHER:     %s\n' "$current_cipher"
 	printf '  PASSWORD:   %s\n\n' "$current_password"
 	printf 'Copy and paste the following command to initialize a cloned repository:\n\n'
-	printf "  transcrypt -c %s -p '%s'\n" "$current_cipher" "$escaped_password"
+	printf "  transcrypt -c %s -p '%s' --md '%s' --use_pbkdf2 '%s' --sm '%s'\n" \
+        "$current_cipher" "$escaped_password" "$current_digest" "$current_use_pbkdf2" "$current_salt_method"
 }
 
 # remove transcrypt-related settings from the repository's git config
@@ -1233,6 +1174,18 @@ help() {
 		            the password to derive the key from;
 		            defaults to 30 random base64 characters
 
+		     -md, --digest=DIGEST
+		            the digest used to hash the salted password;
+		            defaults to md5
+
+		     -pbkdf2, --use_pbkdf2=USE_PBKDF2
+		            Use the pbkdf2 openssl encryption feature;
+		            defaults to 0
+
+		     -sm, --salt_method=SALT_METHOD
+		            Method used to compute deterministic salt; can be password or configured
+		            defaults to password
+
 		     --set-openssl-path=PATH_TO_OPENSSL
 		            use OpenSSL at this path; defaults to 'openssl' in \$PATH
 
@@ -1548,6 +1501,15 @@ get_digest
 get_use_pbkdf2
 get_salt_method
 get_password
+
+if [[ "$salt_method" == "configured" ]]; then
+    extra_salt=$(_load_versioned_config_var "transcrypt.extra-salt")
+    # If we have not configured the extra salt (or we need to rekey), 
+    # then generate new random salt
+    if [[ "$extra_salt" == "" ]] || [[ $rekey ]]; then
+        extra_salt=$(openssl rand -hex 32)
+    fi
+fi
 
 if [[ $rekey ]] && [[ $interactive ]]; then
 	confirm_rekey
